### ISSUE TITLE
Erroneous MathJax expression produced by removing newlines (\n) in math

### ISSUE THREAD

**Issue by jccha** [shd101wyy/mume#50]
This is what I found from an attempt to figure out a solution to [an issue](https://github.com/shd101wyy/markdown-preview-enhanced/issues/806) of markdown-preview-enhanced. 

Description of the problem: for instance, ``$\tilde\nf$`` is translated to ``\tildef``, with ``\n`` removed, inside a MathJax expression.  The following code in ``parse-math.js`` seems to be the relevant part:

```
  } else if (renderingOption === "MathJax") {
    const text = (openTag + content + closeTag).replace(/\n/g, "");
    const tag = displayMode ? "div" : "span";
    return `<${tag} class="mathjax-exps">${escapeString(text)}</${tag}>`;
  } else {
    return "";
```

When I changed ``replace(/\n/g, "")`` to ``replace(/\n/g, " ")``, the problem is resolved.  

Was there some reason to remove ``\n``, instead of the standard TeX convention which replaces ``\n`` with a space?  If not, the code could be fixed as above.

**Comment by kachkaev** [comment]
Thanks a lot for investigating this @jccha! I guess the line you are talking about is this one:

https://github.com/shd101wyy/mume/blame/992ae352656282b41d651d43715fea327feefe81/src/parse-math.ts#L47

After surfing through the mume's history, I can see that this line has been a part of the source since the beginning of times:

https://github.com/shd101wyy/mume/blob/d0323ce19bc9dc7da275b352255d464b3c105b5f/out/src/markdown-engine.js#L145

This means that it is probably safe to replace `\n` with ` ` as you suggest. Feel free to submit a PR!

**Comment by kachkaev** [comment]
Closing since #50 is merged. Thanks again @jccha for reporting and fixing this! 💯
