### ISSUE TITLE
Change .mume/ path

### ISSUE THREAD

**Issue by shd101wyy** [shd101wyy/mume#87]
https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/134

**Comment by ketozhang** [comment]
Hi @shd101wyy 

It's been a while you've touched this issue. I rely on syncing across all my VSCode copies using Settings Sync which ignores `$USERHOME/.mume`.

**Comment by eankeen** [comment]
i was wondering if there were any updates on this?

i think changing it so that we adhere to the xdg base directory specification would be beneficial. so, storing data in `~/.config/mume` instead of ~/.mume`. (or at least checking if a `~/.config/mume` directory exists before writing files in `~/.mume`

as an alternative, maybe you can read in a `$MUME_CONFIG` environment variable and use that instead?

thanks,
edwin

**Comment by shd101wyy** [comment]
Done. Please see the [this PR](https://github.com/shd101wyy/mume/pull/173) offered by @gabyx . 

Thank you guys ;)
