### ISSUE TITLE
Highlighting rows in code blocks

### ISSUE THREAD

**Issue by kachkaev** [shd101wyy/mume#97]
Hi @shd101wyy! 👋 

@jwoLondon and I are wondering if mume can support line highlighting inside the rendered code blocks. You can find examples of this behaviour on this page: https://reactjs.org/tutorial/tutorial.html

Here is the feature at a glance:

> <img width="615" alt="screenshot 2018-11-05 at 22 31 08" src="https://user-images.githubusercontent.com/608862/48030958-8d583d80-e14a-11e8-80cc-2270d6d08106.png">

And here's the raw markdown document:
https://raw.githubusercontent.com/reactjs/reactjs.org/master/content/tutorial/tutorial.md

Highlighted lines of code in the image above are configured this way:

````markdown
```javascript{1,2,6,8}
class Square extends React.Component {
  render() {
    return (
      <button
        className="square"
        onClick={() => this.props.onClick()}
      >
        {this.props.value}
      </button>
    );
  }
}
```
````

I know we can't just go for ` ```javascript{1,2,6,8}` because we've got lots of other code block keywords in mume. However, something like that could be possible:

````markdown
```javascript {highlight=42}
```

```javascript {highlight=10-20}
```

```javascript {highlight=[5,7]}
```

```javascript {highlight=[1-10,15,20-22]}
```

```javascript {highlight=[1-10,15,20-22],something=value}
```
````

The colour of the highlighted background could be done by means of a CSS selector, which would make styling configurable by users.

What do you think?

**Comment by shd101wyy** [comment]
Hi @kachkaev , yeah adding highlighting rows sounds good to me.
For your idea, the followings might not work:
````
```javascript {highlight=10-20}
```

```javascript {highlight=[1-10,15,20-22]}
```

```javascript {highlight=[1-10,15,20-22],something=value}
```
````
because the value of `height` is not a valid javascript object.
I might be wrong about it because I have forgotten the logic in [parse.ts](https://github.com/shd101wyy/mume/blob/master/src/lib/attributes/parse.ts) file.
So I think the followings might be better?

````
```javascript {highlight=[[10,20]]}
```

```javascript {highlight=[[1, 10],15, [20,22]]}
```

```javascript {highlight=[[1, 10],15, [20,22]],something=value}
```
````

---

Not sure, but I feel it is possible to go something like:

````
```javascript {3, 4}
...
```
````

We just need to modify [parser.ts](https://github.com/shd101wyy/mume/blob/master/src/lib/attributes/parse.ts#L14).

---

As for adding highlighting of lines, it seems to me the HTML code generated by `prism.js` doesn't group tokens by lines. 

For example:

````
```c
#include <stdio.h>
int main() {
    printf("Hello World\n");
}
```
````

has generated HTML:

```html
<pre data-role="codeBlock" data-info="c" class="language-c">
  <span class="token macro property">#
    <span class="token directive keyword">include</span> 
    <span class="token string">&lt;stdio.h&gt;</span>
  </span>
  <span class="token keyword">int</span> 
  <span class="token function">main</span>
  <span class="token punctuation">(</span>
  <span class="token punctuation">)</span>
  <span class="token punctuation">{</span>
  <span class="token function">printf</span>
  <span class="token punctuation">(</span>
  <span class="token string">"Hello World\n"</span>
  <span class="token punctuation">)</span>
  <span class="token punctuation">;</span>
  <span class="token punctuation">}</span>
</pre>
```

However, I do see that if we add `.line-numbers` class like below

````
```c {.line-numbers}
#include <stdio.h>
int main() {
    printf("Hello World\n");
}
```
````

The `<pre>...</pre>` includes an extra `span` elements that displays line numbers on the left side of code block:

```html
<pre>
  .. code ..
  <span aria-hidden="true" class="line-numbers-rows">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
  </span>
</pre>
```

So we probably want to do something similar like creating span elements that have `width:100%`.

---

Oh good news, I see there is a line highlight plugin for `prism.js`:

https://prismjs.com/plugins/line-highlight/

So it is possible to implement the feature.

We just need to decide how users should configure lines to highlight.


Thanks!

**Comment by kachkaev** [comment]
[According to our tests](https://github.com/shd101wyy/mume/blob/312e9136daef2d3c124fb643abca8d3035b2b838/test/lib/attributes.test.ts#L108), this syntax should work:

````markdown
```javascript {highlight=10-20}
```

```javascript {highlight=[1-10,15,20-22]}
```

```javascript {highlight=[1-10,15,20-22],something=value}
```
````

They will be parsed into something like:

```json5
{
      highlight: "10-20",
      something: "value",
}

{
      highlight: ["1-10", "15", "20-22"],
}

{
      highlight: ["1-10", "15", "20-22"],
      something: "value",
}
```

We just need another mini-parser right next to the block output code that would turn a string or an array of strings into what's required by https://prismjs.com/plugins/line-highlight/ (if any transformation is at all needed). I don't think that `parser.js` should change in any way for this.

**Comment by kachkaev** [comment]
@shd101wyy WDYT? Would you be happy to give it a go?

**Comment by shd101wyy** [comment]
@kachkaev Sorry for my late response. Yeah that sounds great.
I will only be able to help during the weekdays, but on weekend I should be free.
Thanks.

**Comment by kachkaev** [comment]
@shd101wyy WDYT of this enhancement? Would you be willing to look at it?

**Comment by shd101wyy** [comment]
Sure I will set up a new branch for it tonight.
